In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchsummary import summary
import csv
import numpy as np
import SD2_Model as SD

In [2]:

net = SD.Net()
device = torch.device("cuda") 
net = SD.Net().to(device)
summary(net, input_size = (1,2))
#print(net)

loss_function = nn.MSELoss()
optimizer = optim.Adam(net.parameters(), lr=0.0001)

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                [-1, 1, 20]              60
            Linear-2                [-1, 1, 20]             420
            Linear-3                 [-1, 1, 2]              42
Total params: 522
Trainable params: 522
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [3]:
#dummy data
#trainset = (torch.rand(2,1, device="cuda"), torch.rand(2,1, device="cuda") ) #Xs and Ys
trainset = torch.tensor([[1,2],[3,4]]).to(device)
print(trainset)

tensor([[1, 2],
        [3, 4]], device='cuda:0')


In [4]:
Load_data = True
dataset_path = "../2NN_dataset_flight.2.csv"
if(Load_data):
    trainset = []
    with open(dataset_path) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        for row in csv_reader:
            #feature, data_label = int(row[0:2]),row[2:4]
            feature, data_label = (int(row[0]),int(row[1])),(float(row[2]) * 100 ,float(row[3]) * 100) #convert to cm
            #feature, data_label = (int(row[0]),int(row[1])),(round(float(row[2]) * 100) ,round(float(row[3]) * 100)) #convert to cm
            trainset.append([feature, data_label])
            #print([feature, data_label])

trainset = torch.Tensor(trainset).to(device)
#print(trainset)

test_data = True
if(test_data):
    #trainset = np.array(trainset)
    #print(trainset[1])
    feature, data_label = trainset[0]
    print(feature, data_label)
    #print(feature.view(1,2))
    output = net(feature)
    print(output)



tensor([256., 153.], device='cuda:0') tensor([ 1.1746, -0.1598], device='cuda:0')
tensor([ 6.3309, -7.3105], device='cuda:0', grad_fn=<AddBackward0>)


In [5]:
train = True
epochs = 200
if (train):
    net.train()
    for epoch in range(epochs):
        for data in trainset:  
            feature, data_label = data #
            #print(data)
            #print(feature)
            #print(data_label)
            net.zero_grad()  
            output = net(feature)
            loss = loss_function(output, data_label) 
            loss.backward() 
            optimizer.step() 
        print(epoch,loss)


0 tensor(267.6589, device='cuda:0', grad_fn=<MseLossBackward>)
1 tensor(262.2520, device='cuda:0', grad_fn=<MseLossBackward>)
2 tensor(278.2845, device='cuda:0', grad_fn=<MseLossBackward>)
3 tensor(218.1288, device='cuda:0', grad_fn=<MseLossBackward>)
4 tensor(209.9195, device='cuda:0', grad_fn=<MseLossBackward>)
5 tensor(240.1874, device='cuda:0', grad_fn=<MseLossBackward>)
6 tensor(251.6852, device='cuda:0', grad_fn=<MseLossBackward>)
7 tensor(253.5984, device='cuda:0', grad_fn=<MseLossBackward>)
8 tensor(244.6513, device='cuda:0', grad_fn=<MseLossBackward>)
9 tensor(244.3012, device='cuda:0', grad_fn=<MseLossBackward>)
10 tensor(231.6703, device='cuda:0', grad_fn=<MseLossBackward>)
11 tensor(192.5672, device='cuda:0', grad_fn=<MseLossBackward>)
12 tensor(79.4979, device='cuda:0', grad_fn=<MseLossBackward>)
13 tensor(60.1432, device='cuda:0', grad_fn=<MseLossBackward>)
14 tensor(48.4920, device='cuda:0', grad_fn=<MseLossBackward>)
15 tensor(178.5667, device='cuda:0', grad_fn=<MseLoss

In [8]:
#save network
#save = True
save = False
model_save_path = "2nd_NN.pt"
if (save):
    torch.save(net, model_save_path)

In [7]:
#test evaluate
