In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchsummary import summary
import csv
import numpy as np

In [2]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 20)
        self.fc2 = nn.Linear(20, 20)
        self.fc3 = nn.Linear(20, 2)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

net = Net()
device = torch.device("cuda") 
net = Net().to(device)
summary(net, input_size = (1,2))
#print(net)

loss_function = nn.MSELoss()
optimizer = optim.Adam(net.parameters(), lr=0.0001)

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                [-1, 1, 20]              60
            Linear-2                [-1, 1, 20]             420
            Linear-3                 [-1, 1, 2]              42
Total params: 522
Trainable params: 522
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [3]:
#dummy data
#trainset = (torch.rand(2,1, device="cuda"), torch.rand(2,1, device="cuda") ) #Xs and Ys
trainset = torch.tensor([[1,2],[3,4]]).to(device)
print(trainset)

tensor([[1, 2],
        [3, 4]], device='cuda:0')


In [4]:
Load_data = True
#dataset_path = "../2NN_dataset.csv"
dataset_path = "../2NN_dataset_old_2.csv"
if(Load_data):
    trainset = []
    with open(dataset_path) as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        for row in csv_reader:
            #feature, data_label = int(row[0:2]),row[2:4]
            feature, data_label = (int(row[0]),int(row[1])),(float(row[2]) * 100 ,float(row[3]) * 100) #convert to cm
            #feature, data_label = (int(row[0]),int(row[1])),(round(float(row[2]) * 100) ,round(float(row[3]) * 100)) #convert to cm
            trainset.append([feature, data_label])
            #print([feature, data_label])

## causes error
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

batch = False
if(batch):
    #feature, data_label = trainset[0]
    #print(feature, data_label)
    trainset = chunks(trainset,3)
    trainset = list(trainset)
    #print(list(trainset)[0])
    print(trainset[0])
    



trainset = torch.Tensor(trainset).to(device)
#print(trainset)

test_data = True
if(test_data):
    #trainset = np.array(trainset)
    #print(trainset[1])
    feature, data_label = trainset[0]
    print(feature, data_label)
    #print(feature.view(1,2))
    output = net(feature)
    print(output)



tensor([256., 153.], device='cuda:0') tensor([3.3252, 1.0083], device='cuda:0')
tensor([ 6.7298, 17.4404], device='cuda:0', grad_fn=<AddBackward0>)


In [5]:
train = True
epochs = 200
if (train):
    net.train()
    for epoch in range(epochs):
        for data in trainset:  
            feature, data_label = data #
            #print(data)
            #print(feature)
            #print(data_label)
            net.zero_grad()  
            output = net(feature)
            loss = loss_function(output, data_label) 
            loss.backward() 
            optimizer.step() 
        print(loss)


tensor(1838.5587, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1898.0515, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1810.7115, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1650.7755, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1565.5135, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1518.3279, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1448.7268, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1363.7334, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1283.9303, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1192.9312, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1127.0684, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1067.2832, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(1013.1195, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(962.9987, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(919.2950, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(884.7492, device='cuda:0', grad_fn=<MseLossBackward>)
tensor(851.

In [8]:
#save network
save = True
#save = False
model_save_path = "2nd_NN.pt"
if (save):
    torch.save(net, model_save_path)

In [7]:
#test evaluate
